Repository MicroClub-USTHB/Javascript-language, pull requests merged in 2020-10, with the labels that each got.

#2 added LinkeList data structure
  algorithms/data-structures/LinkedLists.js
Labels: Hacktoberfest

#5 Added Stack and Queue Data Structure
  algorithms/data-structures/Queue.js
  algorithms/data-structures/Stack.js
Labels: Hacktoberfest

#7 Create Factorial (Recursive).js
  algorithms/maths/Factorial (Recursive).js
Labels: hacktoberfest-accepted

#8 Create Factorial.js
  algorithms/maths/Factorial.js
Labels: hacktoberfest-accepted

#6 added path-finding project
  path-finding/README.md
  path-finding/app.js
  path-finding/index.html
  path-finding/style.css
Labels: hacktoberfest-accepted

#9 added bubble sort algorithm
  algorithms/sorting/BubbleSort.js
Labels: Hacktoberfest

#14 Added Radix Sort algorithm
  algorithms/sorting/RadixSort.js
Labels: Hacktoberfest, hacktoberfest-accepted

#17 Classes in JS
  tutorial/Classes/Creating classes.js
  tutorial/Classes/Private fields.js
  tutorial/Classes/inhertance.js
  tutorial/Classes/static fields.js
Labels: Hacktoberfest, hacktoberfest-accepted
